"""
Train PointNet++ SSG Segmentation Model Plugin (PyTorch)

Trains a PointNet++ SSG segmentation model for per-point semantic labeling
using training data (.npz files) generated by the PointNet training data
generation plugin (same format, fully compatible).

Training runs in a background thread with QTimer polling to keep the UI responsive.
"""

import gc
import os
import json
import csv
import time
import threading
import numpy as np
from typing import Dict, Any
from datetime import datetime
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtWidgets, QtCore
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader

import importlib

from plugins.interfaces import ActionPlugin
from config.config import global_variables
from models.pointnet2.pointnet2_seg_model import PointNet2SSGSegmentation
from plugins.dialogs.training_progress_window import TrainingProgressWindow

# Reuse loss functions, dataset, and helpers from PointNet segmentation training
# (numeric directory prefixes require importlib for cross-plugin imports)
_pn_train_mod = importlib.import_module(
    "plugins.060_ML_Models.000_PointNet.010_Segmentation.020_train_seg_model_plugin")
FocalLoss = _pn_train_mod.FocalLoss
DiceLoss = _pn_train_mod.DiceLoss
CombinedFocalDiceLoss = _pn_train_mod.CombinedFocalDiceLoss
SegPointCloudDataset = _pn_train_mod.SegPointCloudDataset
# NOTE: do NOT alias TrainSegModelPlugin at module level — the plugin manager
# would register it as a PointNet2 plugin. Access via _pn_train_mod instead.


class TrainPointNet2SegPlugin(ActionPlugin):
    """Action plugin for training PointNet++ SSG segmentation model."""

    last_params = {
        "training_data_dir": "training_data_seg",
        "output_dir": "models",
        "num_points": 4096,
        "epochs": 100,
        "batch_size": 2,
        "learning_rate": 0.001,
        "val_split": 0.2,
        "early_stopping_patience": 20,
        "loss_function": "Focal + Class Weights",
        "use_scene_validation": True,
        "val_data_dir": "training_data_seg_val",
    }

    def get_name(self) -> str:
        return "train_pointnet2_seg_model"

    def _get_next_run_number(self, output_dir: str) -> int:
        """Get the next run number by scanning existing folders."""
        if not os.path.exists(output_dir):
            return 1
        run_numbers = []
        for item in os.listdir(output_dir):
            if os.path.isdir(os.path.join(output_dir, item)) and item.startswith('seg_pp_run_'):
                try:
                    parts = item.split('_')
                    if len(parts) >= 4:
                        run_num = int(parts[3])
                        run_numbers.append(run_num)
                except (ValueError, IndexError):
                    continue
        return max(run_numbers) + 1 if run_numbers else 1

    def get_parameters(self) -> Dict[str, Any]:
        return {
            "training_data_dir": {
                "type": "directory",
                "default": self.last_params["training_data_dir"],
                "label": "Training Data Directory",
                "description": "Directory containing .npz files (generate via PointNet > Segmentation > Generate Training Data)"
            },
            "output_dir": {
                "type": "directory",
                "default": self.last_params["output_dir"],
                "label": "Output Directory",
                "description": "Directory to save trained model"
            },
            "num_points": {
                "type": "int",
                "default": self.last_params["num_points"],
                "min": 512,
                "max": 16384,
                "label": "Points Per Block",
                "description": "Number of points per training block (must match inference)"
            },
            "epochs": {
                "type": "int",
                "default": self.last_params["epochs"],
                "min": 1,
                "max": 1000,
                "label": "Epochs",
                "description": "Number of training epochs"
            },
            "batch_size": {
                "type": "int",
                "default": self.last_params["batch_size"],
                "min": 1,
                "max": 64,
                "label": "Batch Size",
                "description": "Training batch size (PointNet++ uses more VRAM than PointNet — start with 2)"
            },
            "learning_rate": {
                "type": "float",
                "default": self.last_params["learning_rate"],
                "min": 0.0000001,
                "max": 0.1,
                "decimals": 7,
                "label": "Learning Rate",
                "description": "Initial learning rate"
            },
            "val_split": {
                "type": "float",
                "default": self.last_params["val_split"],
                "min": 0.1,
                "max": 0.5,
                "label": "Validation Split",
                "description": "Fraction of data for validation. When scene validation is on, selects this fraction from the validation folder."
            },
            "use_scene_validation": {
                "type": "bool",
                "default": self.last_params["use_scene_validation"],
                "label": "Use Scene Validation",
                "description": "Use a separate scene folder for validation instead of random split"
            },
            "val_data_dir": {
                "type": "directory",
                "default": self.last_params["val_data_dir"],
                "label": "Validation Data Directory",
                "description": "Directory containing .npz files from a different scene for validation",
                "enabled_by": "use_scene_validation"
            },
            "early_stopping_patience": {
                "type": "int",
                "default": self.last_params["early_stopping_patience"],
                "min": 1,
                "max": 100,
                "label": "Early Stopping Patience",
                "description": "Epochs without improvement before stopping"
            },
            "loss_function": {
                "type": "dropdown",
                "options": {
                    "Cross Entropy": "Cross Entropy (class weighted)",
                    "Focal Loss": "Focal Loss (gamma=2)",
                    "Focal + Class Weights": "Focal Loss + Class Weights (gamma=2)",
                    "Dice Loss": "Dice Loss",
                    "Focal + Dice": "Focal + Dice (combined)",
                },
                "default": self.last_params["loss_function"],
                "label": "Loss Function",
                "description": "Loss function for training"
            },
        }

    def execute(self, main_window, params: Dict[str, Any]) -> None:
        """Execute PointNet++ SSG segmentation training."""
        data_dir = params['training_data_dir'].strip()
        output_dir = params['output_dir'].strip()
        num_points = int(params['num_points'])
        epochs = int(params['epochs'])
        batch_size = int(params['batch_size'])
        learning_rate = float(params['learning_rate'])
        val_split = float(params['val_split'])
        early_stopping_patience = int(params['early_stopping_patience'])
        loss_function = params.get('loss_function', 'Focal + Class Weights')
        use_scene_validation = params.get('use_scene_validation', True)
        val_data_dir = params.get('val_data_dir', '').strip()

        TrainPointNet2SegPlugin.last_params = params.copy()

        if not os.path.exists(data_dir):
            QMessageBox.critical(main_window, "Invalid Directory",
                               f"Training data directory does not exist:\n{data_dir}")
            return

        if use_scene_validation and (not val_data_dir or not os.path.exists(val_data_dir)):
            QMessageBox.critical(main_window, "Invalid Directory",
                               f"Validation data directory does not exist:\n{val_data_dir}")
            return

        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

        run_number = self._get_next_run_number(output_dir)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        folder_name = f"seg_pp_run_{run_number:03d}_{timestamp}"
        unique_output_dir = os.path.join(output_dir, folder_name)
        os.makedirs(unique_output_dir, exist_ok=True)

        random_seed = int(time.time() * 1000) % (2**32)
        np.random.seed(random_seed)
        torch.manual_seed(random_seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed(random_seed)

        print(f"\n{'='*80}")
        print(f"PointNet++ SSG Segmentation Training - Run #{run_number}")
        print(f"{'='*80}")
        print(f"Device: {device}")
        if torch.cuda.is_available():
            print(f"GPU: {torch.cuda.get_device_name(0)}")
        print(f"Random seed: {random_seed}")
        print(f"Output: {unique_output_dir}")

        # --- Setup phase (main thread, fast) ---
        # Reuse helper methods from PointNet training plugin
        _helpers = _pn_train_mod.TrainSegModelPlugin()

        try:
            main_window.disable_menus()
            main_window.disable_tree()
            main_window.tree_overlay.show_processing("Loading training data...")

            npz_files, class_mapping, metadata, num_features = _helpers._load_training_data(data_dir)

            if len(npz_files) == 0:
                QMessageBox.critical(main_window, "No Data",
                                   f"No .npz files found in:\n{data_dir}")
                main_window.tree_overlay.hide_processing()
                main_window.enable_menus()
                main_window.enable_tree()
                return

            num_classes = len(class_mapping)

            # Validate label ranges
            label_min, label_max = 0, 0
            for f in npz_files[:min(20, len(npz_files))]:
                sample_labels = np.load(f)['labels']
                label_min = min(label_min, sample_labels.min())
                label_max = max(label_max, sample_labels.max())
            if label_min < 0 or label_max >= num_classes:
                print(f"WARNING: Labels out of range! Found [{label_min}, {label_max}] "
                      f"but num_classes={num_classes}. Labels will be clamped to [0, {num_classes-1}].")

            print(f"\nDataset: {len(npz_files)} samples")
            print(f"Classes: {num_classes} - {class_mapping}")
            print(f"Features per point: {num_features}")
            print(f"Points per block: {num_points}")
            print(f"Label range in data: [{label_min}, {label_max}]")

            # Get block_size from training data metadata
            block_size = metadata.get('block_size', 10.0)
            print(f"Block size: {block_size}m (from training data metadata)")

            # Split train/val
            main_window.tree_overlay.show_processing("Splitting data...")

            if use_scene_validation:
                train_files = npz_files
                val_npz_files, val_class_mapping, val_metadata, val_num_features = \
                    _helpers._load_training_data(val_data_dir)

                if len(val_npz_files) == 0:
                    QMessageBox.critical(main_window, "No Validation Data",
                                       f"No .npz files found in:\n{val_data_dir}")
                    main_window.tree_overlay.hide_processing()
                    main_window.enable_menus()
                    main_window.enable_tree()
                    return

                if val_num_features != num_features:
                    QMessageBox.critical(main_window, "Feature Mismatch",
                        f"Training data has {num_features} features but "
                        f"validation data has {val_num_features} features.\n\n"
                        f"Both must use the same feature configuration.")
                    main_window.tree_overlay.hide_processing()
                    main_window.enable_menus()
                    main_window.enable_tree()
                    return

                n_val = max(1, int(len(val_npz_files) * val_split))
                np.random.shuffle(val_npz_files)
                val_files = val_npz_files[:n_val]

                print(f"Validation mode: Scene-based (separate folder)")
                print(f"  Train dir: {data_dir} ({len(train_files)} samples)")
                print(f"  Val dir:   {val_data_dir} ({len(val_npz_files)} total, "
                      f"{len(val_files)} sampled at {val_split:.0%})")
            else:
                train_files, val_files = train_test_split(
                    npz_files, test_size=val_split, random_state=random_seed)
                print(f"Validation mode: Random split ({val_split:.0%})")
                print(f"  Training samples: {len(train_files)}")
                print(f"  Validation samples: {len(val_files)}")

            # Compute per-feature standardization stats
            main_window.tree_overlay.show_processing("Computing feature statistics...")
            feature_mean, feature_std = _helpers._compute_feature_stats(train_files)
            print(f"\nPer-feature stats (mean / std):")
            feature_names = ['X_norm', 'Y_norm', 'Z_norm', 'Nx', 'Ny', 'Nz', 'E1', 'E2', 'E3']
            for i in range(len(feature_mean)):
                fname = feature_names[i] if i < len(feature_names) else f"F{i}"
                print(f"  {fname}: mean={feature_mean[i]:.6f}  std={feature_std[i]:.6f}")

            # Find and configure ignored classes
            ignore_classes = _helpers._find_ignore_classes(class_mapping)
            if ignore_classes:
                ignored_names = [class_mapping.get(c, f"Class_{c}") for c in ignore_classes]
                print(f"\nIgnoring classes: {ignore_classes} ({', '.join(ignored_names)})")
            else:
                print(f"\nNo classes to ignore.")

            # Compute class weights
            main_window.tree_overlay.show_processing("Computing class weights...")
            class_weights = _helpers._compute_class_weights(train_files, num_classes)
            for cls_id in ignore_classes:
                if 0 <= cls_id < num_classes:
                    class_weights[cls_id] = 0.0
            class_weights_tensor = torch.FloatTensor(class_weights).to(device)

            print(f"\nClass weights:")
            for cid, weight in enumerate(class_weights):
                name = class_mapping.get(cid, f"Class_{cid}")
                ignored_tag = " (IGNORED)" if cid in ignore_classes else ""
                print(f"  {name}: {weight:.3f}{ignored_tag}")

            # Create datasets and dataloaders
            train_dataset = SegPointCloudDataset(
                train_files, num_points, num_classes, augment=True,
                feature_mean=feature_mean, feature_std=feature_std,
                ignore_classes=ignore_classes)
            val_dataset = SegPointCloudDataset(
                val_files, num_points, num_classes, augment=False,
                feature_mean=feature_mean, feature_std=feature_std,
                ignore_classes=ignore_classes)

            train_loader = DataLoader(
                train_dataset, batch_size=batch_size, shuffle=True,
                num_workers=0, pin_memory=True, drop_last=True)
            val_loader = DataLoader(
                val_dataset, batch_size=batch_size, shuffle=False,
                num_workers=0, pin_memory=True)

            # Create PointNet++ SSG model
            main_window.tree_overlay.show_processing("Creating PointNet++ SSG model...")

            if torch.cuda.is_available():
                torch.cuda.empty_cache()

            model = PointNet2SSGSegmentation(
                num_points=num_points,
                num_features=num_features,
                num_classes=num_classes,
                block_size=block_size
            ).to(device)

            total_params = sum(p.numel() for p in model.parameters())
            print(f"\nModel: PointNet++ SSG — {total_params:,} parameters")
            print(f"Block size: {block_size}m (radii scale accordingly)")

            optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=5e-4)
            scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
                optimizer, mode='max', factor=0.5, patience=5, min_lr=1e-6)

            # Build loss function
            if loss_function == "Cross Entropy":
                criterion = nn.CrossEntropyLoss(
                    weight=class_weights_tensor, ignore_index=-100, label_smoothing=0.1)
            elif loss_function == "Focal Loss":
                criterion = FocalLoss(
                    weight=None, gamma=2.0, ignore_index=-100, label_smoothing=0.1)
            elif loss_function == "Dice Loss":
                criterion = DiceLoss(ignore_index=-100)
            elif loss_function == "Focal + Dice":
                criterion = CombinedFocalDiceLoss(
                    weight=class_weights_tensor, gamma=2.0, ignore_index=-100,
                    label_smoothing=0.1)
            else:  # "Focal + Class Weights" (default)
                criterion = FocalLoss(
                    weight=class_weights_tensor, gamma=2.0, ignore_index=-100,
                    label_smoothing=0.1)
            print(f"Loss function: {loss_function}")

            # Create progress window
            progress_window = TrainingProgressWindow(parent=main_window, total_epochs=epochs)
            progress_window.setWindowTitle(f"PointNet++ SSG Training - Run #{run_number}")
            progress_window.show()
            progress_window.training_started()

            screen_geometry = QtWidgets.QApplication.desktop().screenGeometry()
            x = (screen_geometry.width() - progress_window.width()) // 2
            y = (screen_geometry.height() - progress_window.height()) // 2
            progress_window.move(x, y)

            main_window.tree_overlay.show_processing("Training PointNet++ SSG model...")

        except Exception as e:
            import traceback
            traceback.print_exc()
            QMessageBox.critical(main_window, "Setup Error",
                               f"Failed to set up training:\n\n{str(e)}")
            main_window.tree_overlay.hide_processing()
            main_window.enable_menus()
            main_window.enable_tree()
            return

        # --- Background training thread ---
        training_state = {
            'epoch_results': [],
            'is_running': True,
            'error': None,
            'history': {'loss': [], 'acc': [], 'miou': [], 'val_loss': [], 'val_acc': [], 'val_miou': []},
            'best_val_miou': 0.0,
            'was_cancelled': False,
            'last_epoch': 0,
            'last_val_miou': 0.0,
            'last_val_acc': 0.0,
            'best_val_per_class_iou': {},
            'final_val_per_class_iou': {},
        }

        def _train_loop():
            """Training loop running in background thread."""
            history = training_state['history']
            best_val_miou = 0.0
            epochs_without_improvement = 0

            try:
                for epoch in range(epochs):
                    if progress_window.training_cancelled:
                        training_state['was_cancelled'] = True
                        break

                    # Training phase
                    model.train()
                    train_loss = 0.0
                    train_correct = 0
                    train_total = 0
                    train_batch_count = 0
                    train_confusion = np.zeros((num_classes, num_classes), dtype=np.int64)

                    for batch_features, batch_labels in train_loader:
                        if progress_window.training_cancelled:
                            training_state['was_cancelled'] = True
                            break

                        batch_features = batch_features.to(device)
                        batch_labels = batch_labels.to(device)

                        optimizer.zero_grad()
                        logits = model(batch_features)  # (B, N, C)

                        B, N, C = logits.shape
                        loss = criterion(logits.reshape(B * N, C), batch_labels.reshape(B * N))

                        loss.backward()
                        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
                        optimizer.step()

                        train_loss += loss.item() * B
                        train_batch_count += B
                        preds = torch.argmax(logits, dim=2)
                        valid = batch_labels != -100
                        train_correct += (preds[valid] == batch_labels[valid]).sum().item()
                        train_total += valid.sum().item()

                        _pn_train_mod.TrainSegModelPlugin._update_confusion_matrix(
                            train_confusion, preds, batch_labels, num_classes)

                    if training_state['was_cancelled']:
                        break

                    train_loss /= max(train_batch_count, 1)
                    train_acc = train_correct / max(train_total, 1)
                    train_miou, train_per_class_iou = _pn_train_mod.TrainSegModelPlugin._miou_from_confusion(
                        train_confusion, ignore_classes)

                    # Validation phase
                    model.eval()
                    val_loss = 0.0
                    val_correct = 0
                    val_total = 0
                    val_batch_count = 0
                    val_confusion = np.zeros((num_classes, num_classes), dtype=np.int64)

                    with torch.no_grad():
                        for batch_features, batch_labels in val_loader:
                            batch_features = batch_features.to(device)
                            batch_labels = batch_labels.to(device)

                            logits = model(batch_features)
                            B, N, C = logits.shape
                            loss = criterion(logits.reshape(B * N, C), batch_labels.reshape(B * N))

                            val_loss += loss.item() * B
                            val_batch_count += B
                            preds = torch.argmax(logits, dim=2)
                            valid = batch_labels != -100
                            val_correct += (preds[valid] == batch_labels[valid]).sum().item()
                            val_total += valid.sum().item()

                            _pn_train_mod.TrainSegModelPlugin._update_confusion_matrix(
                                val_confusion, preds, batch_labels, num_classes)

                    val_loss /= max(val_batch_count, 1)
                    val_acc = val_correct / max(val_total, 1)
                    val_miou, val_per_class_iou = _pn_train_mod.TrainSegModelPlugin._miou_from_confusion(
                        val_confusion, ignore_classes)

                    # Update history
                    history['loss'].append(train_loss)
                    history['acc'].append(train_acc)
                    history['miou'].append(train_miou)
                    history['val_loss'].append(val_loss)
                    history['val_acc'].append(val_acc)
                    history['val_miou'].append(val_miou)

                    current_lr = optimizer.param_groups[0]['lr']

                    training_state['epoch_results'].append({
                        'epoch': epoch + 1,
                        'train_loss': train_loss,
                        'train_acc': train_acc,
                        'train_miou': train_miou,
                        'val_loss': val_loss,
                        'val_acc': val_acc,
                        'val_miou': val_miou,
                        'learning_rate': current_lr,
                    })

                    training_state['last_epoch'] = epoch
                    training_state['last_val_miou'] = val_miou
                    training_state['last_val_acc'] = val_acc

                    # Print per-class IoU
                    iou_parts = []
                    for cid in sorted(val_per_class_iou.keys()):
                        name = class_mapping.get(cid, f"C{cid}")
                        iou_parts.append(f"{name}: {val_per_class_iou[cid]:.3f}")
                    if iou_parts:
                        print(f"  Per-class IoU: {' | '.join(iou_parts)}")

                    training_state['final_val_per_class_iou'] = val_per_class_iou.copy()

                    if val_miou > best_val_miou:
                        best_val_miou = val_miou
                        training_state['best_val_per_class_iou'] = val_per_class_iou.copy()
                        epochs_without_improvement = 0

                        torch.save({
                            'epoch': epoch,
                            'model_state_dict': model.state_dict(),
                            'optimizer_state_dict': optimizer.state_dict(),
                            'val_miou': val_miou,
                            'val_acc': val_acc,
                            'class_mapping': class_mapping,
                            'num_points': num_points,
                            'num_features': num_features,
                            'num_classes': num_classes,
                            'block_size': block_size,
                            'model_type': 'PointNet++ SSG',
                            'task_type': 'segmentation',
                            'feature_mean': feature_mean.tolist(),
                            'feature_std': feature_std.tolist(),
                            'ignore_classes': ignore_classes,
                        }, os.path.join(unique_output_dir, 'seg_model_best.pt'))
                    else:
                        epochs_without_improvement += 1

                    scheduler.step(val_miou)

                    if epochs_without_improvement >= early_stopping_patience:
                        print(f"\nEarly stopping after {epoch+1} epochs")
                        break

                training_state['best_val_miou'] = best_val_miou

                # Save final model
                torch.save({
                    'epoch': training_state['last_epoch'],
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'val_miou': training_state['last_val_miou'],
                    'val_acc': training_state['last_val_acc'],
                    'class_mapping': class_mapping,
                    'num_points': num_points,
                    'num_features': num_features,
                    'num_classes': num_classes,
                    'block_size': block_size,
                    'model_type': 'PointNet++ SSG',
                    'task_type': 'segmentation',
                    'history': history,
                    'feature_mean': feature_mean.tolist(),
                    'feature_std': feature_std.tolist(),
                    'ignore_classes': ignore_classes,
                }, os.path.join(unique_output_dir, 'seg_model_final.pt'))

                # Save class mapping
                with open(os.path.join(unique_output_dir, 'class_mapping.json'), 'w') as f:
                    json.dump(class_mapping, f, indent=2)

                # Save training metadata
                training_metadata = {
                    'framework': 'PyTorch',
                    'pytorch_version': torch.__version__,
                    'task_type': 'segmentation',
                    'model_type': 'PointNet++ SSG',
                    'folder_name': folder_name,
                    'timestamp': timestamp,
                    'num_points': num_points,
                    'num_features': num_features,
                    'num_classes': num_classes,
                    'block_size': block_size,
                    'class_mapping': class_mapping,
                    'training_samples': len(train_files),
                    'validation_samples': len(val_files),
                    'epochs_completed': len(history['loss']),
                    'best_val_miou': float(best_val_miou),
                    'final_val_miou': float(history['val_miou'][-1]) if history['val_miou'] else 0.0,
                    'final_val_acc': float(history['val_acc'][-1]) if history['val_acc'] else 0.0,
                    'learning_rate': learning_rate,
                    'batch_size': batch_size,
                    'early_stopping_patience': early_stopping_patience,
                    'validation_split': val_split,
                    'random_seed': random_seed,
                    'run_number': run_number,
                    'source_metadata': metadata,
                    'feature_mean': feature_mean.tolist(),
                    'feature_std': feature_std.tolist(),
                    'ignore_classes': ignore_classes,
                    'best_per_class_iou': {
                        class_mapping.get(cid, f"Class_{cid}"): float(iou)
                        for cid, iou in training_state['best_val_per_class_iou'].items()
                    },
                    'final_per_class_iou': {
                        class_mapping.get(cid, f"Class_{cid}"): float(iou)
                        for cid, iou in training_state['final_val_per_class_iou'].items()
                    },
                }

                with open(os.path.join(unique_output_dir, 'training_metadata.json'), 'w') as f:
                    json.dump(training_metadata, f, indent=2)

                # Write per-class IoU CSV
                try:
                    best_pci = training_state['best_val_per_class_iou']
                    final_pci = training_state['final_val_per_class_iou']
                    csv_path = os.path.join(unique_output_dir, 'per_class_iou.csv')
                    with open(csv_path, 'w', newline='') as f:
                        writer = csv.writer(f)
                        writer.writerow(['class_id', 'class_name', 'iou_at_best_miou', 'final_iou'])
                        for cid in sorted(set(list(best_pci.keys()) + list(final_pci.keys()))):
                            if cid in ignore_classes:
                                continue
                            name = class_mapping.get(cid, f"Class_{cid}")
                            writer.writerow([cid, name,
                                            f"{best_pci.get(cid, 0.0):.6f}",
                                            f"{final_pci.get(cid, 0.0):.6f}"])
                        best_miou = sum(best_pci.values()) / max(len(best_pci), 1)
                        final_miou = sum(final_pci.values()) / max(len(final_pci), 1)
                        writer.writerow(['', 'mIoU', f"{best_miou:.6f}", f"{final_miou:.6f}"])
                    print(f"Per-class IoU saved to: {csv_path}")
                except Exception as csv_err:
                    print(f"Warning: Failed to save per-class IoU CSV: {csv_err}")

            except RuntimeError as e:
                err_str = str(e)
                is_cuda_error = (
                    "out of memory" in err_str.lower() or
                    "CUDNN" in err_str.upper() or
                    "device-side assert" in err_str.lower()
                )
                if is_cuda_error:
                    if torch.cuda.is_available():
                        torch.cuda.empty_cache()
                    if "device-side assert" in err_str.lower():
                        training_state['error'] = (
                            f"CUDA device-side assert at epoch {training_state['last_epoch']+1}.\n\n"
                            f"This usually means label values are out of range for "
                            f"the number of classes ({num_classes}).\n\n"
                            f"Check that training data labels are in [0, {num_classes-1}]."
                        )
                    else:
                        training_state['error'] = (
                            f"GPU memory exceeded.\n\n"
                            f"Current batch_size={batch_size}, num_points={num_points}.\n"
                            f"PointNet++ uses more VRAM than PointNet.\n"
                            f"Try reducing batch size to 1 or points per block."
                        )
                else:
                    training_state['error'] = str(e)
            except Exception as e:
                import traceback
                traceback.print_exc()
                training_state['error'] = str(e)
            finally:
                training_state['is_running'] = False

        # Launch training thread
        thread = threading.Thread(target=_train_loop, daemon=True)
        thread.start()

        # --- QTimer polling (main thread) ---
        poll_timer = QtCore.QTimer()

        def _on_poll():
            """Poll training thread state and update UI."""
            while training_state['epoch_results']:
                result = training_state['epoch_results'].pop(0)
                epoch = result['epoch']

                progress_window.update_epoch(
                    epoch, result['train_loss'], result['train_acc'],
                    result['val_loss'], result['val_acc'],
                    learning_rate=result['learning_rate'],
                    train_miou=result['train_miou'],
                    val_miou=result['val_miou']
                )

                is_new_best = result['val_miou'] >= training_state['best_val_miou']
                best_marker = f"  -> New best model (val_mIoU: {result['val_miou']:.5f})" if is_new_best else ""

                print(f"Epoch {epoch:3d}/{epochs} - "
                      f"loss: {result['train_loss']:.4f} - acc: {result['train_acc']:.4f} - mIoU: {result['train_miou']:.4f} - "
                      f"val_loss: {result['val_loss']:.4f} - val_acc: {result['val_acc']:.4f} - val_mIoU: {result['val_miou']:.4f}"
                      f"{best_marker}")

            if not training_state['is_running']:
                poll_timer.stop()
                _on_training_finished()

        def _on_training_finished():
            """Handle training thread completion on main thread."""
            main_window.tree_overlay.hide_processing()
            main_window.enable_menus()
            main_window.enable_tree()

            history = training_state['history']
            best_val_miou = training_state['best_val_miou']
            was_cancelled = training_state['was_cancelled']
            error = training_state['error']
            epochs_completed = len(history['loss'])

            if error:
                progress_window.training_completed(0.0, cancelled=False)
                progress_window.status_label.setText("Training failed")
            else:
                progress_window.training_completed(best_val_miou, cancelled=was_cancelled)

            progress_window.save_snapshot(
                os.path.join(unique_output_dir, 'training_progress.png'))

            if error:
                print(f"\nERROR during training:\n{error}")
                QMessageBox.critical(progress_window, "Training Error",
                                   f"An error occurred:\n\n{error}")
            elif was_cancelled:
                print(f"\n{'='*80}")
                print("Training Cancelled!")
                print(f"{'='*80}")
                print(f"Best val mIoU: {best_val_miou:.4f}")
                print(f"Epochs completed: {epochs_completed}")
                print(f"Model saved to: {unique_output_dir}/")
                print(f"{'='*80}")
                QMessageBox.information(progress_window, "Training Cancelled",
                    f"Training cancelled.\n\n"
                    f"Best val mIoU: {best_val_miou:.2%}\n"
                    f"Epochs: {epochs_completed}\n\n"
                    f"Saved to:\n{unique_output_dir}/")
            else:
                print(f"\n{'='*80}")
                print("Training Complete!")
                print(f"{'='*80}")
                print(f"Best val mIoU: {best_val_miou:.4f}")
                print(f"Epochs completed: {epochs_completed}")
                print(f"Model saved to: {unique_output_dir}/")
                print(f"{'='*80}")
                QMessageBox.information(progress_window, "Training Complete",
                    f"PointNet++ SSG training completed!\n\n"
                    f"Best val mIoU: {best_val_miou:.2%}\n"
                    f"Epochs: {epochs_completed}\n\n"
                    f"Saved to:\n{unique_output_dir}/")

            # Release RAM and VRAM
            nonlocal model, optimizer, scheduler, criterion
            nonlocal train_dataset, val_dataset, train_loader, val_loader
            nonlocal class_weights_tensor
            model = None
            optimizer = None
            scheduler = None
            criterion = None
            train_dataset = None
            val_dataset = None
            train_loader = None
            val_loader = None
            class_weights_tensor = None
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            gc.collect()
            print("Training memory released (model, datasets, CUDA cache).")

        poll_timer.timeout.connect(_on_poll)
        poll_timer.start(100)
