"""Generate CATALOG.md — one-line purpose per plugin/entity/service/controller.

Walks the four primary code directories (plugins/, core/entities/,
core/services/, application/), parses each .py file via AST, and pulls the
module-level or class-level docstring's first line. Writes CATALOG.md at
the repo root. Re-run any time to refresh.

Why this exists: the project has ~95 plugins + dozens of classes; intent
is not always recoverable from names alone. This catalog is the lightweight
index that makes "what does X do?" cheap to answer without re-reading code.
"""
from __future__ import annotations

import ast
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "CATALOG.md"
SCAN_DIRS = ["plugins", "core/entities", "core/services", "application"]
PLUGIN_BASES = {"Plugin", "AnalysisPlugin", "ActionPlugin"}
SKIP_FILENAMES = {"__init__.py", "interfaces.py"}


def first_line(text: str | None) -> str | None:
    if not text:
        return None
    line = text.strip().split("\n", 1)[0].strip()
    return line or None


def base_name(base: ast.expr) -> str | None:
    if isinstance(base, ast.Name):
        return base.id
    if isinstance(base, ast.Attribute):
        return base.attr
    return None


def is_plugin_class(cls: ast.ClassDef) -> bool:
    return any(base_name(b) in PLUGIN_BASES for b in cls.bases)


def extract_get_name(cls: ast.ClassDef) -> str | None:
    """If the class defines `get_name(self): return "..."`, return that literal."""
    for item in cls.body:
        if isinstance(item, ast.FunctionDef) and item.name == "get_name":
            for stmt in item.body:
                if (
                    isinstance(stmt, ast.Return)
                    and isinstance(stmt.value, ast.Constant)
                    and isinstance(stmt.value.value, str)
                ):
                    return stmt.value.value
    return None


def scan_file(path: Path) -> list[dict]:
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError) as e:
        return [{
            "kind": "error", "name": path.stem,
            "purpose": f"parse error: {e}", "plugin_name": None,
        }]

    module_doc = first_line(ast.get_docstring(tree))
    classes = [n for n in tree.body if isinstance(n, ast.ClassDef)]

    if not classes:
        return [{
            "kind": "module", "name": path.stem,
            "purpose": module_doc, "plugin_name": None,
        }]

    results = []
    for cls in classes:
        cls_doc = first_line(ast.get_docstring(cls))
        kind = "plugin" if is_plugin_class(cls) else "class"
        results.append({
            "kind": kind,
            "name": cls.name,
            "purpose": cls_doc or module_doc,
            "plugin_name": extract_get_name(cls) if kind == "plugin" else None,
        })
    return results


def relpath(p: Path) -> str:
    return p.relative_to(REPO_ROOT).as_posix()


def main() -> None:
    by_dir: dict[Path, list[tuple[Path, list[dict]]]] = defaultdict(list)
    for d in SCAN_DIRS:
        root = REPO_ROOT / d
        if not root.exists():
            continue
        for py in sorted(root.rglob("*.py")):
            if py.name in SKIP_FILENAMES:
                continue
            by_dir[py.parent].append((py, scan_file(py)))

    section_lines: list[str] = []
    total = 0
    missing = 0
    by_kind: dict[str, int] = defaultdict(int)

    def format_entry(entry: dict) -> str:
        nonlocal missing
        label = entry["name"]
        if entry["plugin_name"]:
            label = f'{entry["name"]} → "{entry["plugin_name"]}"'
        purpose = entry["purpose"]
        if not purpose:
            purpose = "**MISSING — add a one-line docstring**"
            missing += 1
        return f"_({entry['kind']})_ **{label}** — {purpose}"

    for d in sorted(by_dir.keys()):
        section_lines.append(f"## `{relpath(d)}/`")
        section_lines.append("")
        for py, entries in by_dir[d]:
            for entry in entries:
                total += 1
                by_kind[entry["kind"]] += 1

            if len(entries) == 1:
                section_lines.append(f"- `{py.name}` {format_entry(entries[0])}")
            else:
                section_lines.append(f"- `{py.name}` — {len(entries)} units in this file:")
                for entry in entries:
                    section_lines.append(f"  - {format_entry(entry)}")
        section_lines.append("")

    kind_summary = ", ".join(f"{v} {k}" for k, v in sorted(by_kind.items()))
    header = [
        "# SPCToolkit Catalog",
        "",
        "_Generated by `tools/generate_catalog.py`. Re-run any time to refresh._",
        "",
        f"**{total} units total** ({kind_summary}). **{missing} missing docstrings** — these are the priority units to document.",
        "",
        "Conventions:",
        "- `(plugin)` — class inherits Plugin / AnalysisPlugin / ActionPlugin (the get_name() string follows the arrow)",
        "- `(class)` — other class",
        "- `(module)` — file with no class definitions (utilities / module-level code)",
        "- **MISSING** — no docstring found anywhere in the file (highest-leverage to fill in first)",
        "",
        "---",
        "",
    ]

    OUTPUT.write_text("\n".join(header + section_lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    print(f"  {total} units total ({kind_summary})")
    print(f"  {missing} missing docstrings")


if __name__ == "__main__":
    main()
